version: "3"

services:
  ssl:
    image: registry.pg3.io:5000/pg3io/ssl:${VERSION:-latest}
    volumes:
#      - /data/ssl/:/sources/
      - ./sources/:/sources/
    environment:
      - "LIST=/sources/list.yml"
#    logging:
#      driver: gelf
#      options:
#        gelf-address: udp://127.0.0.1:12201
#        tag: ssl.status